server:
  port: 8080

spring:
  application:
    name: gateway-microservice

kafka:
  bootstrapAddress: "localhost:9092"
  consumer:
    group: "gateway"
  topic:
    get-account-req: "get-account-request"
    get-account-resp: "get-account-response"
    get-account-balance-req: "get-account-balance-request"
    get-account-balance-resp: "get-account-balance-response"
    create-account-req: "create-account-request"
    create-account-resp: "create-account-response"
    create-transaction-req: "create-transaction-request"
    create-transaction-resp: "create-transaction-response"
    get-transaction-req: "get-transaction-request"
    get-transaction-resp: "get-transaction-response"