server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_bank?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

kafka:
  bootstrapAddress: "localhost:9092"
  consumer:
    group: "account"
  topic:
    create-account-req: "create-account-request"
    create-account-resp: "create-account-response"
    get-account-req: "get-account-request"
    get-account-resp: "get-account-response"
    get-account-balance-req: "get-account-balance-request"
    get-account-balance-resp: "get-account-balance-response"
    update-balance-req: "update-balance-request"
    update-balance-resp: "update-balance-response"
    topup-account-req: "topup-account-request"
    topup-account-resp: "topup-account-response"
