-- Initial SQL Schema for Demo Banking

CREATE DATABASE IF NOT EXISTS demo_bank;
USE demo_bank;

-- Table for Account Service
CREATE TABLE IF NOT EXISTS ACCOUNT_MASTER (
    NIK VARCHAR(255) PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(255),
    CUSTOMER_NAME VARCHAR(255),
    BALANCE DECIMAL(19, 2),
    DATE_CREATED DATETIME
);

-- Tables for Transaction Service
CREATE TABLE IF NOT EXISTS transactions (
    TRANSACTION_ID VARCHAR(255) PRIMARY KEY,
    CREDIT_ACCOUNT VARCHAR(255),
    DEBIT_ACCOUNT VARCHAR(255),
    AMOUNT DECIMAL(19, 2),
    CURRENCY VARCHAR(255),
    STATUS VARCHAR(255),
    DATE_CREATED DATETIME
);

CREATE TABLE IF NOT EXISTS TRANSACTION_HISTORY (
    HISTORY_ID VARCHAR(255) PRIMARY KEY,
    TRANSACTION_ID VARCHAR(255),
    STATUS VARCHAR(255),
    DATE_CREATED DATETIME
);
